server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: junghanso
    password: skan4342
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: sitalk