server:
  port: 80

spring:
  datasource:
    url: sitalk-db.c16gk0kqq71p.ap-northeast-2.rds.amazonaws.com
    username: postgres
    password: skan4342
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect